### ISSUE TITLE
NameError on Rack::QueueMetrics::Middleware

### ISSUE THREAD

**Issue by aceakash** [heroku/rack-queue-metrics#6]
I get an error when I start up my Sinatra app on a Unicorn server:

```
E, [2014-10-23T17:52:48.219194 #62093] ERROR -- : uninitialized constant Rack::QueueMetrics::Middleware (NameError)
/Users/akash/.rvm/gems/ruby-2.0.0-p481/gems/aws-s3-0.6.3/lib/aws/s3/extensions.rb:212:in `const_missing_from_s3_library'
config.ru:11:in `block in <main>'
/Users/akash/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
/Users/akash/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/Users/akash/.rvm/gems/ruby-2.0.0-p481/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `eval'
```

I've got this line in my `Gemfile`:

```
gem "rack-queue-metrics"
```

This is my `config.ru`:

```
require 'rack-queue-metrics'
require 'rubygems'
require 'bundler'

Bundler.require

require './app/main.rb'

use Raindrops::Middleware
use Rack::QueueMetrics::Middleware

run ReportService.new

```

**Comment by CpuID** [comment]
Getting the same thing
